### PR TITLE
Refactor: submodules, loaders

### PR DESCRIPTION
**Pull request by pbailis**
In preparation for increased repo activity, this patch does the following:
  * Migrates to a multi-module format. Core MB operators are in `core`, while new pipelines and features are in `tools` and will migrate to `core` over time. The frontend is in `frontend`.
  * Cleans up the `Ingester` interface. Specifically, we're seeing a lot of activity here, and simplifying ETL will be a big win. We still have `targetLowMetrics` but only three fields for now. Removed `getBaseQuery()`, which is inappropriate for non-SQL loaders.
  * Migrates experimental features to `tools`.

Feedback appreciated. In particular, we could have a separate `experimental` module and a separate `tools` module.

Other notes:
 * This addresses #147 and #156.
 * This should go in after #159. I will resolve the conflicts.
 * This is groundwork for a bunch of code we'll be writing to prepare for the fall quarter (experimental features, rotators, new students, benchmarking).

### CODE REVIEW

**Comment by pbailis** [comment]
@sahaana @kexinrong @edgan8 

@raininthesun: let's talk about this one, there are some issues with Contexts and I'm not sure whether you are planning to rewrite this or if I should put more time into fixing them. (Primarily, strange interactions between the tests and the `DatumEncoder`.

**Comment by raininthesun** [comment]
@pbailis The context code has been stale. I will rebase/rewrite the whole thing once the algorithms are fixed. So you can leave the context code if that do not hold back the refactor.  Can you explain what is strange interactions between the tests and the DatumEncoder?

**Comment by pbailis** [comment]
@kexinrong @edgan8: this is good to go.

**Comment by pbailis** [comment]
@raininthesun: the errors have to with how we encode attributes. In the new code, I've written a helper class that converts generic `attribute`s into contextual attributes, but there's an off-by-one error in one of the tests. Let's see what happens after the rewrite.

**Comment by kexinrong** [comment]
New project structure looks good to me. Quick question: why is `DatumWithNorm` under `macrobase.analysis.result` and `DatumWithScore` under `macrobase.analysis.summary.result`?

**Comment by pbailis** [comment]
Thanks, @kexinrong: I think we can safely remove both of these classes. Working on it now.

**Comment by pbailis** [comment]
@kexinrong: moved `DatumWithNorm` as a protected class of `OutlierClassifier` and removed `DatumWithScore` entirely.

**Comment by pbailis** [comment]
Also pushed a fix that removes `targetLowMetrics` entirely and instead uses a FeatureTransform 😮 🎊 

Now all we have are `metrics` and `attributes`.

**Pull request merged**
