### PR TITLE
ARIMA/NAB updates

### PR DESCRIPTION
**Pull request by viveksjain**
NAB should now actually work again! Running a final evaluation now to see how well it actually performs. Adding `timeColumn` to `targetLowMetrics` seems a little iffy, but fixes ingest for now.

### CODE REVIEW

**Comment by viveksjain** [comment]
Also changed some of @mamikonyana's code. I don't think I broke anything (unless you were using `ScoreDumpDiagnostic` somewhere).

**Comment by mamikonyana** [comment]
Could you rebase off master?

**Comment by viveksjain** [comment]
Hmm was there a force push? I'm traveling for a month and may not have time to look at this, although I will try.

@pbailis did you decide if you're OK with hardcoding timeColumn to be at index 0 of metrics (enforced by the loaders)? Or is there a better way to do it?

**Comment by pbailis** [comment]
Closing for now due to inactivity.

**Pull request closed without merging**
