### PR TITLE
Correct streaming prefix in bench.py

### PR DESCRIPTION
**Pull request by pbailis**
a0658a121a894fb05b613b846684d2fc361b226d had the wrong prefix.

### CODE REVIEW

**Comment by viveksjain** [comment]
LGTM! I like how coveralls fails if coverage stays the same...

**Comment by viveksjain** [comment]
BTW, should we throw an error if an unrecognized flag is used so things like this can't happen?

**Comment by deepakn94** [comment]
I like the idea of throwing an exception if we see an unrecognized flag!

**Comment by pbailis** [comment]
So, this is untested because it's in our Python code.

My only reservation re: putting a check + exception in the Java is that it may limit extensibility. For example, if I add new functionality to a module (or implement my own third party OutlierDetector), now I'll need a separate conf file.

**Comment by deepakn94** [comment]
I think I lost you there? My idea was to have a global list of correct configuration parameter names in the Java configuration class: if you add a new configuration parameter, then you would need to update the global list too.

**Comment by viveksjain** [comment]
I think it's reasonable to ask for all flag names to be in `MacroBaseConf.java`, regardless of where it is used. However, I realize now that this could be annoying if you want to easily switch between versions where one version adds a new flag. At the very least, we could print a warning.

**Comment by pbailis** [comment]
Yeah, I think a warning could be good...

OR

we could have a flag like `macrobase.conf.ignoreUnrecognizedParameters`.

Eh? @viveksjain @deepakn94

**Comment by viveksjain** [comment]
A flag to disable flagging of unrecognized flags?

My general opinion, which you probably already know, is that there should be as few flags as possible - flags can interact in strange ways, and more flags means more code to maintain and more documentation for users to look through. And in this case, shouldn't the logging > loggers config option already handle this?

**Comment by pbailis** [comment]
@viveksjain: cutting commentary... :100: 

If we want few flags and less hassle, isn't the simplest option to allow any flags?

**Comment by viveksjain** [comment]
I probably have the least experience here in terms of working on large scale/long term projects, so take all of my opinion with a grain of salt :). But I would argue displaying warnings for unknown flags *is* less hassle _for the user_, so they know when they're doing the wrong thing.

**Comment by deepakn94** [comment]
LGTM.

**Comment by pbailis** [comment]
d63a8cb6b2e3b1c260e5a6b0c3c3645c706f07cb

**Pull request closed without merging**
