### PR TITLE
Display exceptions in GUI

### PR DESCRIPTION
**Pull request by pbailis**
Adds functionality in the GUI to display exceptions that occur while processing requests in the server.
example-err

Basic implementation idea is to wrap all responses with an extra class with a nullable `errorMessage` field.

### CODE REVIEW

**Comment by pbailis** [comment]
@srmadden!

**Comment by pbailis** [comment]
@sahaana  @kexinrong: good to go!

**Comment by pbailis** [comment]
@kexinrong @sahaana tomorrow, perhaps?

**Comment by kexinrong** [comment]
lgtm

**Pull request merged**
