### PR TITLE
BigDAWG Ingester

### PR DESCRIPTION
**Pull request by mamikonyana**
Create an Ingester that connects to the BIG DAWG database, works with the web UI.

### CODE REVIEW

**Comment by pbailis** [comment]
Since this is a custom ingester, I'd prefer not to put it in the main source tree.

I'm wondering if it's time to create a new Maven submodule (e.g., `tools`) that contains code like this. 

Then, we could support a `DataLoader.CUSTOM` enum, which requires an extra arg `macrobase.loader.class` that can be used to dynamically load the custom loader, as we do with pipelines.

What do you think?

**Comment by mamikonyana** [comment]
I think it's too early to separate custom loaders into a separate submodule. It makes things complicated, but if you really don't want to put this in the main source tree, I could try creating a new submodule, but I'm worried that it will become stale soon after we do that.

**Comment by pbailis** [comment]
@mamikonyana: do you still want to merge this?

**Comment by pbailis** [comment]
(Unintentionally closed, sorry!)

**Comment by pbailis** [comment]
@mamikonyana do you have plans to merge this?

**Comment by mamikonyana** [comment]
I was under impression you didn't want this.. If you want this merged, I can update the revision to work with new repository setup.

**Comment by pbailis** [comment]
Closing for now.

**Pull request closed without merging**
