### PR TITLE
Allow specifying auxilaryAttributes 

### PR DESCRIPTION
**Pull request by mamikonyana**
which get dumped with the rest of data, very heplful for ploting performance

### CODE REVIEW

**Comment by pbailis** [comment]
Got it. Kind of messy, but probably okay. @deepakn94: thoughts?

@viveksjain is going to add another way to specify a column as time so I'm curious if there is a more generic way we want to handle this.

**Comment by viveksjain** [comment]
From #64: `timeColumn, attributes, lowMetrics, highMetrics` are used together in a bunch of places - maybe it's worth refactoring them out into a single wrapper class.
It's not really a more generic way to handle this, more like duct tape to hide the excrescence. Maybe convert the rest to something like a DataTransformation so you have inversion of control? And then you could have have a wrapper class containing a List<DataTransformation>.

BTW, this is probably going to cause merge conflicts with #64, but since my branch already has merge conflicts I'm going to wait for this one to go in first.

**Comment by viveksjain** [comment]
And I'd prefer any refactoring to be done after #64 is in.

**Comment by mamikonyana** [comment]
Cool. I like the idea of putting all those variables in a wrapper.
I'll wait for a word from @deepakn94 and merge this after that.

**Comment by deepakn94** [comment]
Sure, we can put these in a wrapper class.

**Comment by pbailis** [comment]
Sure, we can do a refactoring push after #64.
@viveksjain: more incentive to get it in!

**Pull request closed without merging**
