### PR TITLE
Add a way to specify password/user for benchmarking scripts…

### PR DESCRIPTION
**Pull request by mamikonyana**
…also tweaks to parameter storage

@deepakn94 could you take a look?

### CODE REVIEW

**Comment by mamikonyana** [comment]
I moved configurations into their own `.json` files, i hope you don't mind

**Comment by deepakn94** [comment]
What's the behavior like if the `USER` environment variable isn't set?
Otherwise, LGTM.

**Comment by mamikonyana** [comment]
I didn't test that, I'll add a fail safe to default to postgres. but `USER` is set automatically on linux and Mac, so that shouldn't be a problem.

**Comment by mamikonyana** [comment]
I actually set the default to None, in that case dbUser will be ignored in the config file.

**Comment by deepakn94** [comment]
Alright, sounds good. Thanks!

**Pull request merged**
