### PR TITLE
Configuration refactoring.

### PR DESCRIPTION
**Pull request by pbailis**
This patch addresses #76 and #38, in line with the discussion on #76. This breaks just about everything, but the resulting code is much, much cleaner.

The code is tested through the GUI and the scripts. I've updated the configuration variables in each script as well.

I moved the score dumping to a separate `test/diagnostic` class. See `bin/diagnostic.sh` and try running `bin/diagnostic.sh dump` to test it out. In general, this will allow us to set up diagnostic tests that we may not want to have in the main source tree but are nevertheless very useful.

### CODE REVIEW

**Comment by pbailis** [comment]
@deepakn94 @mamikonyana @viveksjain: This may take a while, but can one of you take a look?

**Comment by pbailis** [comment]
@deepakn94 and I were discussing the number of weird formatting issues in the repo. As long as we're having a massive code churn, I added another commit to do a pass of mostly automated reformatting of code.

So:
7a7a7aefecabd9af193d4212c7f8efc44533e13a has the refactoring.
1783e1e0e475f2b9d23d88d8feeea0510af9ee67 has the reformatting.

**Comment by deepakn94** [comment]
"Files changed: 96"

**Comment by deepakn94** [comment]
Looks good from a quick pass. Thanks for doing this!
Just hope everything works as before :P

**Comment by pbailis** [comment]
Thanks, @deepakn94. Will respond to individual comments and push fixes later today.

**Comment by pbailis** [comment]
AFAICT, this does seem to work on the existing scripts. The primary changes to them were renaming config variables.

**Comment by pbailis** [comment]
TODO for myself: put in sanity checking (e.g., of Booleans) again...

**Comment by viveksjain** [comment]
Thanks for seeing this through! What did you use for the automatic reformatting? Might be worth checking in the script/IDE formatting configuration file.

**Comment by pbailis** [comment]
I used IntelliJ's automatic "Reformat Code" functionality -- I used the defaults! It would be good to set up some auto-format / auto-lint test too. @deepakn94 was also interested.

**Comment by deepakn94** [comment]
Went through this really quickly again. LGTM.

**Pull request merged**
