### PR TITLE
Allow specifying JDBC properties in a config file as a dictionary

### PR DESCRIPTION
**Pull request by mamikonyana**

### CODE REVIEW

**Comment by pbailis** [comment]
Is there a reason why this patch subclasses `PostgreIngester` instead of just adding a new configuration flag?

**Comment by mamikonyana** [comment]
You'd prefer to have an option to pass a dictionary of properties that we'd like to use as JDBC properties?

**Comment by mamikonyana** [comment]
@pbailis

**Comment by pbailis** [comment]
LGTM; pls squash commits before merge.

**Pull request closed without merging**
