### PR TITLE
Dead code eliminination; Caching SQL loader test.

### PR DESCRIPTION
**Pull request by pbailis**
Should be an easy PR.

Eliminates dead code, adds a test to CachingSQLLoader.

### CODE REVIEW

**Comment by mamikonyana** [comment]
I created a gzip file loader for my test, I'd recommend using that instead of checking in a 10K line long csv

**Comment by pbailis** [comment]
@mamikonyana: fixed, thanks for the tip!

BTW, `src/test/resources/data/2d_standard_normal_100k.csv.gz` is 1.8MB compressed :) We may want to only use a sample...

**Comment by pbailis** [comment]
Also, @mamikonyana is this good to go? :v:

**Comment by mamikonyana** [comment]
lgtm

**Pull request merged**
