### PR TITLE
REST Server for lib functionality

### PR DESCRIPTION
**Pull request by pbailis**

### CODE REVIEW

**Comment by pbailis** [comment]
@edgan8 good to go

**Comment by pbailis** [comment]
After conversations with @fabuzaid21, we decided to put both a generic `Pipeline` class and the REST server under a new module called `core`. Therefore, `cli` depends on `core` (and only `core`, not `lib`), and new pipelines can be put into `core`, too, without affecting lib.

Alternatives we discussed closely:
 * Put pipelines in `lib` (problem: since `lib` is our "stable" makes it very high bar to add more pipelines)
 * Duplicate pipeline functionality in `cli` and `server` (problem: if we add new pipelines, they'll be incompatible across CLI and the REST API)
 * Create a separate `pipeline` package (problem: seems overkill in terms of resulting dependencies -- `server` -> `pipeline` -> `lib`)

Apache Spark also uses the `server`-equivalent in its `core`, and the new Spark web framework makes it much more lightweight.

**Comment by edgan8** [comment]
Having 3 levels of dependencies could get clunky to manage. I think either or both of

a) merging cli and core into one package (core) 
b) putting pipelines in lib and commenting that they are unstable until ready

would in practice be way more convenient

**Comment by pbailis** [comment]
Following the discussion with @sahaana and @fabuzaid21, confirming we will put pipelines in `core` along with `cli`, with experimental modules also in `core` but clearly delineated as such. @edgan8 do you feel comfortable finishing this refactoring?

**Comment by pbailis** [comment]
I think it'd be awesome to have an annotation like @Experimental as in RxJava (http://reactivex.io/RxJava/javadoc/rx/annotations/Experimental.html) or Apache Spark (https://spark.apache.org/docs/1.4.0/api/java/org/apache/spark/annotation/Experimental.html)

**Comment by edgan8** [comment]
Sounds good. An annotation would work great, and I am also happy with annotating the class javadocs for now.

**Comment by edgan8** [comment]
I'm currently updating this to fold cli into core. Also taking this chance to unify the configuration / query objects for the cli and server pipelines.

**Comment by edgan8** [comment]
@fabuzaid21 @jialinding curious what you guys think about this refactoring

**Pull request merged**
