### PR TITLE
Use log density as score for Mixture models

### PR DESCRIPTION
**Pull request by mamikonyana**
This allows to run them with percentileClassifier, because percentile classifier needs high values for outliers not small.

### CODE REVIEW

**Comment by mamikonyana** [comment]
@pbailis could you take a look?

**Comment by mamikonyana** [comment]
java changes are in #134, this are changes to accompanying scripts to run inference and plot, not necessarily only for those changes.

**Comment by pbailis** [comment]
@mamikonyana why not combine?

**Comment by pbailis** [comment]
LGTM, would prefer to squash with existing PR, though.

**Comment by mamikonyana** [comment]
I was using this scripts in other branch and I really didn't want to have merge conflicts when I squashed the other PR.

**Pull request closed without merging**
